# Generated by Django 4.2.26 on 2026-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("fulltime", "Full-Time"),
                        ],
                        default="fulltime",
                        max_length=20,
                    ),
                ),
                ("required_skills", models.JSONField(default=list)),
                ("source_url", models.URLField(blank=True)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
