# Generated by Django 4.2.26 on 2026-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("target_role", models.CharField(blank=True, max_length=200)),
                ("available_hours_per_week", models.PositiveIntegerField(default=10)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("fulltime", "Full-Time"),
                        ],
                        default="internship",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
